channels:
# - defaults
- conda-forge
dependencies:
- sphinx==4.5.0
- sphinxcontrib-napoleon==0.7
- nbsphinx==0.8.8
- pip:
  - sphinx-rtd-theme==1.0.0
  - git+https://github.com/jupyter/jupyter-sphinx.git@v0.3.1