datasets:
  raw:
    orders:
      type: ds
      format: csv
      uri: data/raw/sales/orders.csv
      driver_params: {}
      
    housing:
      type: ds
      format: csv
      uri: data/raw/housing/housing.csv
      driver_params: {}
  
    product:
      type: ds
      format: csv
      uri: data/raw/sales/prod_master.csv
      driver_params: {}
  
  cleaned:
    orders:
      type: ds
      format: parquet
      uri: data/cleaned/sales/orders.parquet
      driver_params: {}

    product:
      type: ds
      format: parquet
      uri: data/cleaned/sales/product.parquet
      driver_params: {}

    sales:
      type: ds
      format: parquet
      uri: data/cleaned/sales/sales.parquet
      driver_params: {}

  processed:
    sales:
      type: ds
      format: parquet
      uri: data/processed/sales/sales.parquet
      driver_params: {}

  train:
    housing:
      features:
        type: ds
        format: parquet
        uri: housing reposts/train/housing/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: housing reposts/train/housing/target.parquet
        driver_params:
          save:
            index: False
    sales:
      features:
        type: ds
        format: parquet
        uri: housing reposts/train/sales/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: housing reposts/train/sales/target.parquet
        driver_params:
          save:
            index: False
  test:
    housing:
      features:
        type: ds
        format: parquet
        uri: housing reposts/test/housing/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: housing reposts/test/housing/target.parquet
        driver_params:
          save:
            index: False
    sales:
      features:
        type: ds
        format: parquet
        uri: housing reposts/test/sales/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: housing reposts/test/sales/target.parquet
        driver_params:
          save:
            index: False
  score:
    housing:
      output:
        type: ds
        format: parquet
        uri: housing reposts/housing/scored_output.parquet
        driver_params:
          save:
            index: False